#!/usr/bin/ash

run_earlyhook() {
    if [ -e /consolecolors ]
    then
        setcolors -c /dev/console /consolecolors
    else
        msg "No consolecolors found despite added hook."
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
